//! Compile the vendored mandoc render-only subset (`vendor/mandoc`) plus the C
//! bridge into a static lib the crate links.
//!
//! mandoc normally fills `config.h` by running `./configure`, which *executes*
//! probe programs — impossible when cross-compiling. So we synthesise config.h
//! ourselves, keyed to the target libc family (gnu / musl / darwin / mingw),
//! exactly the way the spike's hand-written config.h did for mingw. The HAVE_*
//! flags decide which of mandoc's bundled `compat_*.c` shims compile in (each is
//! `#if !HAVE_x`, so a present feature yields an empty object) and which
//! prototypes config.h must declare for the ones we *do* provide.

use std::path::PathBuf;

/// Which libc functions the target provides natively (true ⇒ use the system
/// one, no compat shim, no prototype). Only the flags that vary by libc.
struct Have {
    err: bool,
    getline: bool,
    getsubopt: bool,
    progname: bool,
    reallocarray: bool,
    recallocarray: bool,
    strcasestr: bool,
    strlcat: bool,
    strlcpy: bool,
    strndup: bool,
    strsep: bool,
    strtonum: bool,
    vasprintf: bool,
    strptime: bool,
    /// wide-char surface (`<wchar.h>`, putwc, …) — true on every target here.
    wchar: bool,
    /// `wcwidth(3)` specifically: mingw lacks it (we compile the Kuhn shim).
    wcwidth: bool,
}

fn have_for(os: &str, env: &str) -> Have {
    // Baseline = a modern glibc/BSD-ish libc: most things present.
    let mut h = Have {
        err: true,
        getline: true,
        getsubopt: true,
        progname: false, // getprogname/setprogname is BSD/darwin-only
        reallocarray: true,
        recallocarray: false, // OpenBSD-only
        strcasestr: true,
        strlcat: false, // glibc lacks the strl* pair
        strlcpy: false,
        strndup: true,
        strsep: true,
        strtonum: false, // BSD-only
        vasprintf: true,
        strptime: true,
        wchar: true,
        wcwidth: true,
    };
    match (os, env) {
        ("linux", "musl") => {
            // musl ≥1.2.2 ships strlcpy/strlcat; the rest matches glibc.
            h.strlcat = true;
            h.strlcpy = true;
        }
        ("macos", _) | ("ios", _) => {
            // darwin libc has the BSD string helpers and getprogname, but the
            // SDK the cross stdenv targets doesn't expose reallocarray — take it
            // from compat (mandoc_aux.c calls it).
            h.progname = true;
            h.strlcat = true;
            h.strlcpy = true;
            h.reallocarray = false;
        }
        ("windows", _) => {
            // mingw: take everything from mandoc's compat_*.c.
            h = Have {
                err: false,
                getline: false,
                getsubopt: false,
                progname: false,
                reallocarray: false,
                recallocarray: false,
                strcasestr: false,
                strlcat: false,
                strlcpy: false,
                strndup: false,
                strsep: false,
                strtonum: false,
                vasprintf: false,
                strptime: false,
                wchar: true,
                wcwidth: false, // mingw has no wcwidth → compile the Kuhn shim
            };
        }
        _ => {} // linux-gnu and anything else: the glibc baseline above
    }
    h
}

fn b(v: bool) -> u8 {
    u8::from(v)
}

fn gen_config_h(h: &Have) -> String {
    let mut s = String::new();
    s.push_str(
        "/* Generated by build.rs — render-only mandoc config, no ./configure. */\n\
         #ifdef __cplusplus\n#error \"Do not use C++.\"\n#endif\n\n\
         #define _GNU_SOURCE\n\
         #include <sys/types.h>\n\
         #include <stdio.h>\n\
         #include <stdarg.h>\n\n\
         #define MAN_CONF_FILE \"man.conf\"\n\
         #define MANPATH_BASE \"\"\n\
         #define MANPATH_DEFAULT \"\"\n\
         #define OSENUM MANDOC_OS_OTHER\n\
         #define UTF8_LOCALE \".UTF-8\"\n\
         #define OSNAME \"Unpin\"\n\n\
         #ifndef EFTYPE\n#define EFTYPE EINVAL\n#endif\n\
         #ifndef O_DIRECTORY\n#define O_DIRECTORY 0\n#endif\n\
         #ifndef PATH_MAX\n#define PATH_MAX 4096\n#endif\n\n\
         /* Structural features unused by the render subset — keep them off. */\n\
         #define HAVE_DIRENT_NAMLEN 0\n\
         #define HAVE_ENDIAN 0\n\
         #define HAVE_SYS_ENDIAN 0\n\
         #define HAVE_NTOHL 0\n\
         #define HAVE_FTS 0\n\
         #define HAVE_FTS_COMPARE_CONST 0\n\
         #define HAVE_LESS_T 0\n\
         #define HAVE_MKDTEMP 0\n\
         #define HAVE_MKSTEMPS 0\n\
         #define HAVE_PLEDGE 0\n\
         #define HAVE_SANDBOX_INIT 0\n\
         #define HAVE_STRINGLIST 0\n\
         #define HAVE_REWB_BSD 0\n\
         #define HAVE_REWB_SYSV 1\n\
         #define HAVE_ISBLANK 1\n\
         #define HAVE_OHASH 0\n\
         #define NEED_XPG4_2 0\n\
         #define HAVE_MMAP 0\n\
         #define HAVE_ZLIB 0\n\n",
    );

    // The libc-varying HAVE_* flags.
    s.push_str(&format!("#define HAVE_ERR {}\n", b(h.err)));
    s.push_str(&format!("#define HAVE_GETLINE {}\n", b(h.getline)));
    s.push_str(&format!("#define HAVE_GETSUBOPT {}\n", b(h.getsubopt)));
    s.push_str(&format!("#define HAVE_PROGNAME {}\n", b(h.progname)));
    s.push_str(&format!("#define HAVE_REALLOCARRAY {}\n", b(h.reallocarray)));
    s.push_str(&format!("#define HAVE_RECALLOCARRAY {}\n", b(h.recallocarray)));
    s.push_str(&format!("#define HAVE_STRCASESTR {}\n", b(h.strcasestr)));
    s.push_str(&format!("#define HAVE_STRLCAT {}\n", b(h.strlcat)));
    s.push_str(&format!("#define HAVE_STRLCPY {}\n", b(h.strlcpy)));
    s.push_str(&format!("#define HAVE_STRNDUP {}\n", b(h.strndup)));
    s.push_str(&format!("#define HAVE_STRSEP {}\n", b(h.strsep)));
    s.push_str(&format!("#define HAVE_STRTONUM {}\n", b(h.strtonum)));
    s.push_str(&format!("#define HAVE_VASPRINTF {}\n", b(h.vasprintf)));
    s.push_str(&format!("#define HAVE_STRPTIME {}\n", b(h.strptime)));
    s.push_str(&format!("#define HAVE_WCHAR {}\n\n", b(h.wchar)));

    // Prototypes for every compat function we compile in (HAVE_x == 0). The
    // system headers don't declare these (that's why they're absent), so config.h
    // must — mandoc's real config.h does exactly the same.
    s.push_str("/* prototypes for the compiled-in compat_*.c shims */\n");
    if !h.err {
        s.push_str(
            "extern void err(int, const char *, ...);\n\
             extern void errx(int, const char *, ...);\n\
             extern void warn(const char *, ...);\n\
             extern void warnx(const char *, ...);\n",
        );
    }
    if !h.getline {
        s.push_str("extern ssize_t getline(char **, size_t *, FILE *);\n");
    }
    if !h.getsubopt {
        s.push_str("extern int getsubopt(char **, char * const *, char **);\n");
    }
    if !h.progname {
        s.push_str(
            "extern const char *getprogname(void);\n\
             extern void setprogname(const char *);\n",
        );
    }
    if !h.reallocarray {
        s.push_str("extern void *reallocarray(void *, size_t, size_t);\n");
    }
    if !h.recallocarray {
        s.push_str("extern void *recallocarray(void *, size_t, size_t, size_t);\n");
    }
    if !h.strcasestr {
        s.push_str("extern char *strcasestr(const char *, const char *);\n");
    }
    if !h.strlcat {
        s.push_str("extern size_t strlcat(char *, const char *, size_t);\n");
    }
    if !h.strlcpy {
        s.push_str("extern size_t strlcpy(char *, const char *, size_t);\n");
    }
    if !h.strndup {
        s.push_str("extern char *strndup(const char *, size_t);\n");
    }
    if !h.strsep {
        s.push_str("extern char *strsep(char **, const char *);\n");
    }
    if !h.strtonum {
        s.push_str("extern long long strtonum(const char *, long long, long long, const char **);\n");
    }
    if !h.vasprintf {
        s.push_str("extern int vasprintf(char **, const char *, va_list);\n");
    }
    if !h.wcwidth {
        s.push_str("extern int wcwidth(int);\t/* Kuhn shim — mingw has none */\n");
    }
    s
}

/// The parse + terminal-format closure (CORE + MAN + MDOC + TBL + EQN), minus
/// `wcwidth_shim.c` (added conditionally) and `term_tag.c` (stubbed in bridge.c).
const SUBSET: &[&str] = &[
    "roff.c", "roff_validate.c", "roff_term.c", "read.c", "mandoc.c",
    "mandoc_aux.c", "mandoc_msg.c", "mandoc_ohash.c", "mandoc_xr.c", "preconv.c",
    "tag.c", "chars.c", "msec.c", "lib.c", "att.c", "arch.c", "st.c", "term.c",
    "term_ascii.c", "out.c", "term_tab.c", "man.c", "man_macro.c",
    "man_validate.c", "man_term.c", "mdoc.c", "mdoc_macro.c", "mdoc_validate.c",
    "mdoc_argv.c", "mdoc_state.c", "mdoc_term.c", "tbl.c", "tbl_data.c",
    "tbl_layout.c", "tbl_opts.c", "tbl_term.c", "eqn.c", "eqn_term.c",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let vendor = manifest.join("vendor/mandoc");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    let have = have_for(&os, &env);

    std::fs::write(out.join("config.h"), gen_config_h(&have)).expect("write config.h");

    let mut build = cc::Build::new();
    build
        .include(&out) // generated config.h
        .include(&vendor)
        .define("_GNU_SOURCE", None)
        .warnings(false)
        .flag_if_supported("-fno-strict-aliasing");
    for f in SUBSET {
        build.file(vendor.join(f));
    }
    // mandoc's bundled fallbacks define a libc function unconditionally (no
    // internal `#if HAVE_x` guard), so — like mandoc's own configure — compile
    // each only when the target lacks it. Compiling, say, compat_strlcpy.c where
    // the libc already has strlcpy clashes with darwin's _FORTIFY_SOURCE macro
    // and risks duplicate definitions elsewhere. compat_ohash is always needed
    // (HAVE_OHASH is 0 on every target).
    let compat: &[(&str, bool)] = &[
        ("compat_ohash.c", true),
        ("compat_strlcpy.c", !have.strlcpy),
        ("compat_strlcat.c", !have.strlcat),
        ("compat_strndup.c", !have.strndup),
        ("compat_reallocarray.c", !have.reallocarray),
        ("compat_recallocarray.c", !have.recallocarray),
        ("compat_vasprintf.c", !have.vasprintf),
        ("compat_getline.c", !have.getline),
        ("compat_strsep.c", !have.strsep),
        ("compat_strcasestr.c", !have.strcasestr),
        ("compat_strtonum.c", !have.strtonum),
        ("compat_getsubopt.c", !have.getsubopt),
        ("compat_progname.c", !have.progname),
        ("compat_err.c", !have.err),
    ];
    for (f, needed) in compat {
        if *needed {
            build.file(vendor.join(f));
        }
    }
    build.file(vendor.join("bridge.c"));
    if !have.wcwidth {
        build.file(vendor.join("wcwidth_shim.c"));
    }
    build.compile("unpinmandoc");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=vendor/mandoc");
}
